### ISSUE TITLE
Chatroom notification support

### ISSUE THREAD

**Issue by tsiemens** [wwade/jobrunner#47]
As previously discussed, built-in support for chat-room notifications (like gchat) is desirable.

I've been giving some thought to how to properly implement this. We can track important points of this discussion in this issue.

My initial thoughts:
- Must be implemented in its own binary. In order to properly make use of the existing job infra, like is done with mail right now, the feature must be its invoked via its own binary.
- I'm not sure how yet how heavily the current mail code should be used. Surely the chat binary will receive some arguments plus information from its stdin, as mail does, but undecided on if it needs to share mail's interface.
- Not sure if the feature should overload the `-m` option of `job`. If it does, most likely the cc option won't work, which is perhaps fine.
- Configuration probably will want to be stored in jobrc, however this will require that the chat binary be passed the any relevant options used by the Config class. This would require a couple things:
  1. `job` would need to be aware that it is dealing with the chat binary, and pass through the options (so we'd probably not be just setting the chat binary into mail.program. Perhaps there would be a mail.type=mail|chat or mail.useChat=true|false, or something of that nature)
  2. `Config` should probably take kwargs rather than the the argparse options object directly, so it's a bit more portable OR a subset of `job`'s arg parser should be commonly available to both scripts. This could also be fine.
- Making this script not so tightly integrated such that a user could have some wrapper around both it and mail for on-the-fly determination of using chat or mail is also on my mind (having `job` pass through some if its options makes this a bit more annoying). Maybe this is mostly silly and doesn't need to be thought of (other than maybe making `job` consider that if "cc" or "to" options are given to override the default notification type and use the mail program).

The complete alternative is writing a fully separate chat mail-semi-compatible script also distributed through pip, which has its own rc file, etc. This is still kind of a hack, but at least that project would be designed with the purpose of being a hack for other tools.

Would like to hear some more thoughts on this.

**Comment by tsiemens** [comment]
I have a candidate for this feature. Would appreciate a looksee before I dig into unit tests.

https://github.com/wwade/jobrunner/compare/master...tsiemens:chatmail?expand=1

**Comment by wwade** [comment]
Yeah, looks great, @tsiemens, thanks!

**Comment by wwade** [comment]
Fixed in #49
